### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by shubhamnarlawar**

### CODE REVIEW

**Comment by shubhamnarlawar** [comment]
`cargo build` in rust runtime leads to - 

```
          libstd-68b25ab3829cbbae.rlib(std-68b25ab3829cbbae.std.e9qr3pyf-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol ReadConsoleW referenced in function _ZN65_$LT$std..sys..windows..stdio..Stdin$u20$as$u20$std..io..Read$GT$4read17h62735753429fe8c5E
          libstd-68b25ab3829cbbae.rlib(std-68b25ab3829cbbae.std.e9qr3pyf-cgu.0.rcgu.o) : error LNK2001: unresolved external symbol "const type_info::`vftable'" (??_7type_info@@6B@)
          libpanic_unwind-dd86b2a9657509c7.rlib(panic_unwind-dd86b2a9657509c7.panic_unwind.c096yiyw-cgu.0.rcgu.o) : error LNK2001: unresolved external symbol "const type_info::`vftable'" (??_7type_info@@6B@)
          libpanic_unwind-dd86b2a9657509c7.rlib(panic_unwind-dd86b2a9657509c7.panic_unwind.c096yiyw-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol _CxxThrowException referenced in function _ZN12panic_unwind8real_imp5panic17h826f7a0728b29a81E
          libcore-3cedc7817d8eb468.rlib(core-3cedc7817d8eb468.core.bazh2akg-cgu.0.rcgu.o) : error LNK2001: unresolved external symbol _fltused
          C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86\advapi32.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
          C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86\ws2_32.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
          C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86\userenv.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
          C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\lib\x86\msvcrt.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
          C:\nballerina\runtime\rust_rt\target\debug\build\proc-macro2-b292688f57b12159\build_script_build-b292688f57b12159.exe : fatal error LNK1120: 131 unresolved externals


error: aborting due to previous error

error: could not compile `proc-macro2`
```

**Comment by shubhamnarlawar** [comment]
Here is the latest windows weekly build - https://github.com/shubhamnarlawar/nballerina/runs/2790258491?check_suite_focus=true

**Comment by shubhamnarlawar** [comment]
@KavinduZoysa - Can you please guve your suggestions on this PR

**Comment by manuranga** [comment]
Closing since project is moving to attic.

**Pull request closed without merging**
