### PR TITLE
Fix static_cast warnings in BIR Reader and ConstantPool

### LINKED ISSUE #318: Fix static_cast warnings in compiler/reader
Fix warnings invoked by Clang-tidy in -

```
a. compiler/include/reader/BIRFileReader.h
b. compiler/reader/BIRFileReader.cpp
c. compiler/reader/BIRReadPackage.cpp
d. compiler/reader/ConstantPool.cpp
```

### PR DESCRIPTION
**Pull request by shubhamnarlawar**
Resolves #318

### CODE REVIEW

**Comment by ruvi-d** [comment]
@shubhamnarlawar : I think you should at least  use assert to check whether the dynamic cast was successful. Otherwise we are not getting a benefit from the additional overhead associated with the dynamic cast( vs static casts).

**Comment by shubhamnarlawar** [comment]
> @shubhamnarlawar : I think you should at least use assert to check whether the dynamic cast was successful. Otherwise we are not getting a benefit from the additional overhead associated with the dynamic cast( vs static casts).

I tried to put a assert statement before a dynamic_cast as below - 

```
        assert(dynamic_cast<PackageCpInfo *>(poolEntry));
        auto *packageEntry = dynamic_cast<PackageCpInfo *>(poolEntry);
```

Its passing. Should I put a assert statement before every dynamic_cast?

**Comment by ruvi-d** [comment]
> Its passing. Should I put a assert statement before every dynamic_cast?

Assert after every dynamic cast like this:
```
auto *packageEntry = dynamic_cast<PackageCpInfo *>(poolEntry);
assert(packageEntry);
```

**Comment by shubhamnarlawar** [comment]
> > Its passing. Should I put a assert statement before every dynamic_cast?
> 
> Assert after every dynamic cast like this:
> 
> ```
> auto *packageEntry = dynamic_cast<PackageCpInfo *>(poolEntry);
> assert(packageEntry);
> ```

Done. Thanks!

**Review by ruvi-d — APPROVED** [review]

**Comment by shubhamnarlawar** [comment]
@KavinduZoysa - Shall we merge this PR

**Comment by manuranga** [comment]
Closeing since project is moving to attic

**Pull request closed without merging**
